import Head from "next/head";
import { Input } from '@fluentui/react-components';
import { Card } from "@fluentui/react-components/unstable";
import { makeStyles, shorthands } from "@fluentui/react-components";
import { Stack, StackItem } from "@/components/stack";

const useStyles = makeStyles({
  card: {
    ...shorthands.margin("48px"),
    ...shorthands.borderRadius("4px"),
    height: "600px",
  },
  leftPanel: {
    width: "200px",
  },
  main: {
    backgroundImage: 'url("/website-background.png")',
  },
});

export default function Home() {
  const styles = useStyles();
  return (
    <>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Card className={styles.card}>
          <Stack
            overrideStyles={{
              flexDirection: "row",
              justifyContent: "center",
              alignContent: "center",
            }}
            overrideItemStyles={{ margin: "10px", width: "100%" }}
          >
            <StackItem>
              <Stack>
                <StackItem>
                  <div
                    style={{
                      fontSize: "48px",
                      lineHeight: "48px",
                      marginTop: "20px",
                      marginBottom: "20px",
                    }}
                  >
                    Hello, <br /> Traveler
                  </div>
                </StackItem>
                <StackItem>
                  <Stack overrideStyles={{ marginTop: '20px', marginBottom: '20px'}}>
                    {["Link1", "Link2", "Link3"].map((text) => (
                      <StackItem>{text}</StackItem>
                    ))}
                  </Stack>
                </StackItem>
                <StackItem overrideItemStyles={{ marginBottom: '0px' }}>
                  <Input type="search" placeholder="Search" />
                </StackItem>
              </Stack>
            </StackItem>
          </Stack>
        </Card>
      </main>
    </>
  );
}
